# Generated by Django 4.0 on 2022-09-06 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Описание вашей идеи.', max_length=5000, verbose_name='Текст')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('scale', models.CharField(choices=[('ПОД', 'Подъезд'), ('ДВО', 'Двор'), ('РАЙ', 'Район'), ('ГОР', 'Город'), ('ОБЛ', 'Область'), ('СТР', 'Страна')], default='ПОД', max_length=3)),
                ('flag', models.BooleanField(verbose_name='Принята ли ваша идея')),
                ('coordinate_x', models.FloatField(default=None, help_text='По этим коориднатам будет отражаться метка вашей идеи.', verbose_name='Координаты места')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='auth.user')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
    ]
